language: go

go:
  - 1.7

matrix:
  fast_finish: true

before_install:
  - openssl aes-256-cbc -pass "pass:${PEM_DECRYPTION_KEY}" -in .extension -out extension.pem -d -a
  - go get github.com/aktau/github-release
  - sudo apt-get install jq
  - >-
    cd /usr/local/bin/ &&
    curl -LO https://cdn.rawgit.com/GoogleChrome/chrome-app-samples/cf768bbcbd0553dbe21197beb481e0371258b0a5/samples/dojo/crxmake.sh &&
    chmod +x crxmake.sh
  - cd ${TRAVIS_BUILD_DIR}

script:
  - >-
    if [ ${job} == 'first' ]; then
      github-release release
       --tag "v.${TRAVIS_COMMIT}"
       --name "v.${TRAVIS_COMMIT}"
       --description ""
    fi
  - >-
    export name=`cat ${app}/manifest.json | jq -r .name`
    export description=`cat ${app}/manifest.json | jq -r .description`
    crxmake.sh ${app} extension.pem &&
    github-release upload
     --tag "v.${TRAVIS_COMMIT}"
     --name ${name}
     --file ${app}.crx

env:
  matrix:
    - app='bitrix' job='first'
    - app='couchpotato'
    - app='bitrix'
    - app='deluge'
    - app='google-calendar'
    - app='headphones'
    - app='labiomed-mail'
    - app='plex'
    - app='sonarr' job='last'
    