language: generic

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - jq

before_install:
  - cd /usr/local/bin/
  - sudo curl -LO https://cdn.rawgit.com/GoogleChrome/chrome-app-samples/cf768bbcbd0553dbe21197beb481e0371258b0a5/samples/dojo/crxmake.sh
  - sudo chmod +x crxmake.sh
  - cd ${TRAVIS_BUILD_DIR}
  - openssl aes-256-cbc -pass "pass:${PEM_DECRYPTION_KEY}" -in extension.pem.enc -out extension.pem -d -a

install:
  - >-
    for app in */; do
      export name=`cat ${app}/manifest.json | jq -r .name` &&
      export description=`cat ${app}/manifest.json | jq -r .description` &&
      crxmake.sh ${app} extension.pem;
    done

before_deploy:
  - git tag -a "v.${TRAVIS_COMMIT}" -m "Release v.${TRAVIS_COMMIT}"

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file:
    - bitrix.crx
    - couchpotato.crx
    - deluge.crx
    - google-calendar.crx
    - headphones.crx
    - la-biomed-mail.crx
    - plex.crx
    - sonarr.crx
  skip_cleanup: true
  on:
    tags: true
